-- MySQL Script generated by MySQL Workbench
-- Sun Sep 13 23:31:48 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema films
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema films
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `films` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `films` ;

-- -----------------------------------------------------
-- Table `films`.`age_limit_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `films`.`age_limit_info` (
  `age_limit_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `description` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`age_limit_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `films`.`films_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `films`.`films_info` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `duration_min` INT NULL DEFAULT NULL,
  `year_of_issue` INT NULL DEFAULT NULL,
  `age_limit` INT NULL DEFAULT NULL,
  `film_description` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `age_limit_idx` (`age_limit` ASC) VISIBLE,
  CONSTRAINT `age_limit`
    FOREIGN KEY (`age_limit`)
    REFERENCES `films`.`age_limit_info` (`age_limit_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `films`.`award_inf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `films`.`award_inf` (
  `id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `films`.`award`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `films`.`award` (
  `film_id` INT NOT NULL AUTO_INCREMENT,
  `year` VARCHAR(45) NOT NULL,
  `award_inf_id` INT UNSIGNED NOT NULL,
  INDEX `film_id_idx` (`film_id` ASC) VISIBLE,
  INDEX `fk_award_award_inf1_idx` (`award_inf_id` ASC) VISIBLE,
  CONSTRAINT `_film_id`
    FOREIGN KEY (`film_id`)
    REFERENCES `films`.`films_info` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_award_award_inf1`
    FOREIGN KEY (`award_inf_id`)
    REFERENCES `films`.`award_inf` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 23
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `films`.`box_area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `films`.`box_area` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `films`.`country_dict`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `films`.`country_dict` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 65
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `films`.`director_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `films`.`director_info` (
  `director_id` INT NOT NULL,
  `director_fullname` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`director_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `films`.`director`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `films`.`director` (
  `film_id` INT NOT NULL,
  `director_id` INT NULL DEFAULT NULL,
  INDEX `film_id_idx` (`film_id` ASC) VISIBLE,
  INDEX `director_id_idx` (`director_id` ASC) VISIBLE,
  CONSTRAINT `director_id`
    FOREIGN KEY (`director_id`)
    REFERENCES `films`.`director_info` (`director_id`),
  CONSTRAINT `F_film_id`
    FOREIGN KEY (`film_id`)
    REFERENCES `films`.`films_info` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `films`.`emp_sales_result`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `films`.`emp_sales_result` (
  `emp_nm` VARCHAR(30) NOT NULL,
  `division_cd` VARCHAR(15) NOT NULL,
  `result_cnt` INT NULL DEFAULT NULL,
  `result_amt` INT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `films`.`film_box`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `films`.`film_box` (
  `film_id` INT NOT NULL,
  `area_id` INT NOT NULL,
  `box in area (m.d.)` FLOAT NULL DEFAULT NULL,
  INDEX `film_id` (`film_id` ASC) VISIBLE,
  INDEX `area_id_idx` (`area_id` ASC) VISIBLE,
  CONSTRAINT `area_id`
    FOREIGN KEY (`area_id`)
    REFERENCES `films`.`box_area` (`id`),
  CONSTRAINT `film_box_ibfk_1`
    FOREIGN KEY (`film_id`)
    REFERENCES `films`.`films_info` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `films`.`film_production`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `films`.`film_production` (
  `film_id` INT NOT NULL,
  `country_id` INT NOT NULL,
  INDEX `film_id_idx` (`film_id` ASC) VISIBLE,
  INDEX `country_id_idx` (`country_id` ASC) VISIBLE,
  CONSTRAINT `country_id`
    FOREIGN KEY (`country_id`)
    REFERENCES `films`.`country_dict` (`id`),
  CONSTRAINT `f_id`
    FOREIGN KEY (`film_id`)
    REFERENCES `films`.`films_info` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `films`.`genre_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `films`.`genre_info` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `genre_name` VARCHAR(50) NULL DEFAULT NULL,
  `genre_description` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `films`.`genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `films`.`genre` (
  `film_id` INT NOT NULL,
  `genre_id` INT NOT NULL,
  INDEX `genre_id_idx` (`genre_id` ASC) VISIBLE,
  INDEX `_film_id_` (`film_id` ASC) VISIBLE,
  CONSTRAINT `_film_id_`
    FOREIGN KEY (`film_id`)
    REFERENCES `films`.`films_info` (`id`),
  CONSTRAINT `genre_id`
    FOREIGN KEY (`genre_id`)
    REFERENCES `films`.`genre_info` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `films`.`most_similar_movies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `films`.`most_similar_movies` (
  `film_id` INT NULL DEFAULT NULL,
  `most_similar_film` INT NULL DEFAULT NULL,
  INDEX `film_id` (`film_id` ASC) VISIBLE,
  INDEX `most_similar_film` (`most_similar_film` ASC) VISIBLE,
  CONSTRAINT `most_similar_movies_ibfk_1`
    FOREIGN KEY (`film_id`)
    REFERENCES `films`.`films_info` (`id`),
  CONSTRAINT `most_similar_movies_ibfk_2`
    FOREIGN KEY (`most_similar_film`)
    REFERENCES `films`.`films_info` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `films`.`rating_inf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `films`.`rating_inf` (
  `rating_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`rating_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `films`.`rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `films`.`rating` (
  `film_id` INT NULL DEFAULT NULL,
  `rating_category` INT NULL DEFAULT NULL,
  `ratingl` FLOAT NULL DEFAULT NULL,
  INDEX `film_id` (`film_id` ASC) VISIBLE,
  INDEX `rating_category_idx` (`rating_category` ASC) VISIBLE,
  CONSTRAINT `rating_category`
    FOREIGN KEY (`rating_category`)
    REFERENCES `films`.`rating_inf` (`rating_id`),
  CONSTRAINT `rating_ibfk_1`
    FOREIGN KEY (`film_id`)
    REFERENCES `films`.`films_info` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `films`.`staffinfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `films`.`staffinfo` (
  `emp_id` INT NOT NULL AUTO_INCREMENT,
  `emp_nm` VARCHAR(20) NOT NULL,
  `birth_dt` DATE NOT NULL,
  `start_dt` DATE NOT NULL,
  `end_dt` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`emp_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `films`.`studio_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `films`.`studio_info` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 62
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `films`.`studio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `films`.`studio` (
  `film_id` INT NOT NULL,
  `studio_id` INT NOT NULL,
  INDEX `studio_id_idx` (`studio_id` ASC) VISIBLE,
  INDEX `film_id_` (`film_id` ASC) VISIBLE,
  CONSTRAINT `film_id_`
    FOREIGN KEY (`film_id`)
    REFERENCES `films`.`films_info` (`id`),
  CONSTRAINT `studio_id`
    FOREIGN KEY (`studio_id`)
    REFERENCES `films`.`studio_info` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
